### ISSUE TITLE
Does not load under IE11 / Windows 10

### ISSUE THREAD

**Issue by jgoldhammer** [jelbourn/material2-app#3]
One of the main focus of material2 should be that the app is working in IE11 and Windows 10, so that the ui-framework can be used in all kinds of enterprise apps...

Thanks,
Jens

**Comment by jgoldhammer** [comment]
![2016-03-27_21-33-08](https://cloud.githubusercontent.com/assets/3872101/14067348/ba65a956-f463-11e5-9535-b48588bfb22b.png)

**Comment by jelbourn** [comment]
I can load up the latest version on IE11, looks to be fixed.
