### ISSUE TITLE
this example is not working at all

### ISSUE THREAD

**Issue by mInzamamMalik** [jelbourn/material2-app#43]
I was looking for Angular Material working example(too good if with angular 4 and material2 beta3)

this example is not working at all
II tried `npm install`, `npm install --only-dev` and `npm start`

![image](https://cloud.githubusercontent.com/assets/14273842/24967053/44b052b6-1fc2-11e7-9475-57e88f2486c8.png)

![image](https://cloud.githubusercontent.com/assets/14273842/24967101/6f53d376-1fc2-11e7-81bc-a14b8f784f7f.png)

**Comment by kjhatis** [comment]
Leave your Package.json so i can take look of dependencies

**Comment by kjhatis** [comment]
Try this you seems missing the Angular/Animations modules `npm i @angular/animation` . 
also set correct path for deeppurple-amber.css might fix your issue

**Comment by mInzamamMalik** [comment]
thanks
